name: Deploy

on: 
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get netlify context
        id: context
        run: |
          echo ::set-output name=context::$(python .github/scripts/netlify.py
           "${{ secrets.NETLIFY_SITE_ID }}" "${{ github.sha }}" --context)

      # If the event is not a pull request then set the deployment to production or else to preview.
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: ${{ steps.context.outputs.context }}
          ref: ${{ github.head_ref }}

      - name: Get netlify url
        id: url
        run: |
          echo ::set-output name=url::$(python .github/scripts/netlify.py
           "${{ secrets.NETLIFY_SITE_ID }}" "${{ github.sha }}")

      - name: Get state
        id: state
        run: |
          echo ::set-output name=state::$([ ${{ steps.url.outputs.url }} == "failure" ]
           && echo "failure" || echo "success")
      
      - uses: chrnorm/deployment-status@releases/v1
        if: ${{ steps.state.outputs.state }} == "failure" || ${{ steps.url.outputs.url }} == ""
        name: Update the deployment' state without url
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          state: ${{ steps.state.outputs.state }}
      
      - uses: chrnorm/deployment-status@releases/v1
        if: ${{ steps.state.outputs.state }} != "failure" || ${{ steps.url.outputs.url }} != ""
        name: Update the deployment' state with url
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          target_url: ${{ steps.url.outputs.url }}
          environment_url: ${{ steps.url.outputs.url }}
          state: ${{ steps.state.outputs.state }}

      # Update the organizations's README profile only if the deployment is in production.
      - name: Update website screenshot
        if: github.event_name != 'pull_request'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Screenshot
          repo: findaclip/branding
          token: ${{ secrets.PERSONAL_TOKEN }}
