name: Deploy

on: 
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # If the event is not a pull request then set the deployment to production.
      - uses: chrnorm/deployment-action@releases/v1
        if: github.event_name != 'pull_request'
        name: Create GitHub production deployment
        id: prod_deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: Production
      
      # If the event is a pull request then set the deployment to preview.
      - uses: chrnorm/deployment-action@releases/v1
        if: github.event_name == 'pull_request'
        name: Create GitHub production deployment
        id: dev_deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: Preview

      - name: Wait for Netlify deployment
        id: wait
        uses: probablyup/wait-for-netlify-action@3.2.0
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
          max_timeout: 120
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      # Update the production deployment' state to success.
      - uses: chrnorm/deployment-action@releases/v1
        if: github.event_name != 'pull_request'
        name: Update the production deployment' state
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_url: https://findaclip.netlify.app/
          deployment_id: ${{ steps.prod_deployment.outputs.deployment_id }}
          state: "success"
      
      # If the event is a pull request then set the deployment to preview.
      - uses: chrnorm/deployment-action@releases/v1
        if: github.event_name == 'pull_request'
        name: Update the preview deployment' state
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          target_url: ${{ steps.wait.outputs.url }}
          deployment_id: ${{ steps.dev_deployment.outputs.deployment_id }}
          state: "success"

      # Update the organizations's README profile only if the deployment is in production.
      - name: Update website screenshot
        if: github.event_name != 'pull_request'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Screenshot
          repo: findaclip/branding
          token: ${{ secrets.PERSONAL_TOKEN }}
