name: Deploy

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for Netlify Deploy
        id: waitForDeployment
        uses: probablyup/wait-for-netlify-action@3.2.0
        with:
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
          max_timeout: 120
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      
      - name: Deployment url
        run: echo "${{ steps.waitForDeployment.outputs.url }}"

      # - name: Update website screenshot
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: Screenshot
      #     repo: findaclip/branding
      #     token: ${{ secrets.PERSONAL_TOKEN }}
